import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={montserrat.className}>
        <nav>
          <h1>My Navbar</h1>
          <ol>
            <li>
              <Link href='/about'>About</Link>
            </li>
          </ol>
        </nav>
        {children}
        <footer>
          <h1>My Sharona</h1>
        </footer>
      </body>
    </html>
  );
}
